{{- if .Values.dashboard.allowedIps }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-ipallowlist
spec:
  ipAllowList:
    sourceRange:
    {{- range .Values.dashboard.allowedIps }}
      - {{ . }}
    {{- end }}
{{- end -}}
