{{- include "ingressroute" (dict "name" "prometheus" "hostname" .Values.dashboard.hostname "allowedIps" .Values.dashboard.allowedIps "serviceName" "prometheus-prometheus-server" "servicePort" "http") -}}
