letsencrypt:
  email: "" # Has to be specified

cloudflare:
  apiToken: "" # Has to be specified

cert-manager:
  replicaCount: 2

  podDisruptionBudget:
    enabled: true
    minAvailable: 50%

  crds:
    enabled: true

  dns01RecursiveNameserversOnly: true
  dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"